language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t ianronbowden/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ianronbowden/react-test npm test -- --coverage

after_success:
  - docker build -t ianronbowden/multi-client ./client
  - docker build -t ianronbowden/multi-nginx ./nginx
  - docker build -t ianronbowden/multi-server ./server
  - docker build -t ianronbowden/multi-worker ./worker
  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push ianronbowden/multi-client
  - docker push ianronbowden/multi-nginx
  - docker push ianronbowden/multi-server
  - docker push ianronbowden/multi-worker

 deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-768721002619'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY